// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ProductSearch
type ProductSearchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSearchRequest) Reset()         { *m = ProductSearchRequest{} }
func (m *ProductSearchRequest) String() string { return proto.CompactTextString(m) }
func (*ProductSearchRequest) ProtoMessage()    {}
func (*ProductSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *ProductSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSearchRequest.Unmarshal(m, b)
}
func (m *ProductSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSearchRequest.Marshal(b, m, deterministic)
}
func (m *ProductSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSearchRequest.Merge(m, src)
}
func (m *ProductSearchRequest) XXX_Size() int {
	return xxx_messageInfo_ProductSearchRequest.Size(m)
}
func (m *ProductSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSearchRequest proto.InternalMessageInfo

func (m *ProductSearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProductSearchResponse struct {
	Results              []*Result `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProductSearchResponse) Reset()         { *m = ProductSearchResponse{} }
func (m *ProductSearchResponse) String() string { return proto.CompactTextString(m) }
func (*ProductSearchResponse) ProtoMessage()    {}
func (*ProductSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *ProductSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSearchResponse.Unmarshal(m, b)
}
func (m *ProductSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSearchResponse.Marshal(b, m, deterministic)
}
func (m *ProductSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSearchResponse.Merge(m, src)
}
func (m *ProductSearchResponse) XXX_Size() int {
	return xxx_messageInfo_ProductSearchResponse.Size(m)
}
func (m *ProductSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSearchResponse proto.InternalMessageInfo

func (m *ProductSearchResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type Result struct {
	ProductUuid          string   `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uom                  string   `protobuf:"bytes,4,opt,name=uom,proto3" json:"uom,omitempty"`
	Indexes              []*Index `protobuf:"bytes,5,rep,name=indexes,proto3" json:"indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetProductUuid() string {
	if m != nil {
		return m.ProductUuid
	}
	return ""
}

func (m *Result) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Result) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Result) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

func (m *Result) GetIndexes() []*Index {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type Index struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{3}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*ProductSearchRequest)(nil), "server.ProductSearchRequest")
	proto.RegisterType((*ProductSearchResponse)(nil), "server.ProductSearchResponse")
	proto.RegisterType((*Result)(nil), "server.Result")
	proto.RegisterType((*Index)(nil), "server.Index")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e) }

var fileDescriptor_453745cff914010e = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0x69, 0x52, 0x9d, 0xb6, 0x22, 0x43, 0x85, 0x50, 0x2c, 0xd4, 0xbd, 0x18, 0x3c,
	0xe4, 0x50, 0x3f, 0x81, 0x47, 0x2f, 0x22, 0x2b, 0x82, 0x37, 0x89, 0xd9, 0x41, 0x03, 0x36, 0x1b,
	0xf7, 0x8f, 0xe8, 0x17, 0xf1, 0xf3, 0x4a, 0x67, 0xbb, 0x15, 0xc5, 0xde, 0x66, 0x7e, 0x6f, 0x79,
	0xfb, 0x78, 0x03, 0x63, 0x4b, 0xb5, 0x69, 0x5e, 0xaa, 0xde, 0x68, 0xa7, 0x31, 0xb7, 0x64, 0xde,
	0xc9, 0x88, 0x0b, 0x98, 0xde, 0x1a, 0xad, 0x7c, 0xe3, 0xee, 0x58, 0x96, 0xf4, 0xe6, 0xc9, 0x3a,
	0x44, 0x18, 0x74, 0xf5, 0x8a, 0x8a, 0x64, 0x91, 0x94, 0x87, 0x92, 0x67, 0x71, 0x05, 0x27, 0x7f,
	0xde, 0xda, 0x5e, 0x77, 0x96, 0xb0, 0x84, 0xa1, 0x21, 0xeb, 0x5f, 0x9d, 0x2d, 0xb2, 0x45, 0x5a,
	0x8e, 0x96, 0x47, 0x55, 0xb0, 0xaf, 0x24, 0x63, 0x19, 0x65, 0xf1, 0x95, 0x40, 0x1e, 0x18, 0x9e,
	0xc1, 0xb8, 0x0f, 0x6e, 0x8f, 0xde, 0xb7, 0x6a, 0xf3, 0xd3, 0x68, 0xc3, 0xee, 0x7d, 0xab, 0x70,
	0x06, 0x07, 0x4d, 0xed, 0xe8, 0x59, 0x9b, 0xcf, 0x62, 0x9f, 0xe5, 0xed, 0xbe, 0x0d, 0x98, 0xfe,
	0x04, 0xc4, 0x63, 0x48, 0xbd, 0x5e, 0x15, 0x03, 0x46, 0xeb, 0x11, 0xcf, 0x61, 0xd8, 0x76, 0x8a,
	0x3e, 0x28, 0x26, 0x9b, 0xc4, 0x64, 0xd7, 0x6b, 0x2c, 0xa3, 0x2a, 0xe6, 0x90, 0x31, 0xc1, 0x29,
	0x64, 0xcc, 0x38, 0x4f, 0x26, 0xc3, 0xb2, 0x7c, 0x80, 0x3c, 0xd4, 0x87, 0x37, 0x30, 0xf9, 0x55,
	0x02, 0x9e, 0x46, 0xc7, 0xff, 0x7a, 0x9c, 0xcd, 0x77, 0xa8, 0xa1, 0x39, 0xb1, 0xf7, 0x94, 0xf3,
	0x3d, 0x2e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xab, 0x3b, 0x94, 0x9f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchClient interface {
	ProductSearch(ctx context.Context, in *ProductSearchRequest, opts ...grpc.CallOption) (*ProductSearchResponse, error)
}

type searchClient struct {
	cc *grpc.ClientConn
}

func NewSearchClient(cc *grpc.ClientConn) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) ProductSearch(ctx context.Context, in *ProductSearchRequest, opts ...grpc.CallOption) (*ProductSearchResponse, error) {
	out := new(ProductSearchResponse)
	err := c.cc.Invoke(ctx, "/server.search/ProductSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
type SearchServer interface {
	ProductSearch(context.Context, *ProductSearchRequest) (*ProductSearchResponse, error)
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_ProductSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ProductSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.search/ProductSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ProductSearch(ctx, req.(*ProductSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProductSearch",
			Handler:    _Search_ProductSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
