// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supply.proto

package server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CreateOrder
type CreateOrderRequest struct {
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Foreman              string   `protobuf:"bytes,4,opt,name=foreman,proto3" json:"foreman,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CreateOrderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOrderRequest) GetForeman() string {
	if m != nil {
		return m.Foreman
	}
	return ""
}

func (m *CreateOrderRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateOrderResponse struct {
	Order                *OrderSummary `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{1}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrder() *OrderSummary {
	if m != nil {
		return m.Order
	}
	return nil
}

// AddOrderItem
type AddOrderItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uom                  string   `protobuf:"bytes,4,opt,name=uom,proto3" json:"uom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderItemRequest) Reset()         { *m = AddOrderItemRequest{} }
func (m *AddOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddOrderItemRequest) ProtoMessage()    {}
func (*AddOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{2}
}

func (m *AddOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderItemRequest.Unmarshal(m, b)
}
func (m *AddOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *AddOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderItemRequest.Merge(m, src)
}
func (m *AddOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddOrderItemRequest.Size(m)
}
func (m *AddOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderItemRequest proto.InternalMessageInfo

func (m *AddOrderItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *AddOrderItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddOrderItemRequest) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

type AddOrderItemResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderItemResponse) Reset()         { *m = AddOrderItemResponse{} }
func (m *AddOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddOrderItemResponse) ProtoMessage()    {}
func (*AddOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{3}
}

func (m *AddOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderItemResponse.Unmarshal(m, b)
}
func (m *AddOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *AddOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderItemResponse.Merge(m, src)
}
func (m *AddOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddOrderItemResponse.Size(m)
}
func (m *AddOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderItemResponse proto.InternalMessageInfo

func (m *AddOrderItemResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// RemoveOrderItem
type RemoveOrderItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrderItemRequest) Reset()         { *m = RemoveOrderItemRequest{} }
func (m *RemoveOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveOrderItemRequest) ProtoMessage()    {}
func (*RemoveOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{4}
}

func (m *RemoveOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrderItemRequest.Unmarshal(m, b)
}
func (m *RemoveOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *RemoveOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrderItemRequest.Merge(m, src)
}
func (m *RemoveOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveOrderItemRequest.Size(m)
}
func (m *RemoveOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrderItemRequest proto.InternalMessageInfo

func (m *RemoveOrderItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoveOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type RemoveOrderItemResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrderItemResponse) Reset()         { *m = RemoveOrderItemResponse{} }
func (m *RemoveOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveOrderItemResponse) ProtoMessage()    {}
func (*RemoveOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{5}
}

func (m *RemoveOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrderItemResponse.Unmarshal(m, b)
}
func (m *RemoveOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *RemoveOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrderItemResponse.Merge(m, src)
}
func (m *RemoveOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveOrderItemResponse.Size(m)
}
func (m *RemoveOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrderItemResponse proto.InternalMessageInfo

func (m *RemoveOrderItemResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// ModifyRequestedQuantity
type ModifyRequestedQuantityRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequestedQuantityRequest) Reset()         { *m = ModifyRequestedQuantityRequest{} }
func (m *ModifyRequestedQuantityRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRequestedQuantityRequest) ProtoMessage()    {}
func (*ModifyRequestedQuantityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{6}
}

func (m *ModifyRequestedQuantityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Unmarshal(m, b)
}
func (m *ModifyRequestedQuantityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Marshal(b, m, deterministic)
}
func (m *ModifyRequestedQuantityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequestedQuantityRequest.Merge(m, src)
}
func (m *ModifyRequestedQuantityRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Size(m)
}
func (m *ModifyRequestedQuantityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequestedQuantityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequestedQuantityRequest proto.InternalMessageInfo

func (m *ModifyRequestedQuantityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ModifyRequestedQuantityRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ModifyRequestedQuantityRequest) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ModifyRequestedQuantityResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequestedQuantityResponse) Reset()         { *m = ModifyRequestedQuantityResponse{} }
func (m *ModifyRequestedQuantityResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyRequestedQuantityResponse) ProtoMessage()    {}
func (*ModifyRequestedQuantityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{7}
}

func (m *ModifyRequestedQuantityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Unmarshal(m, b)
}
func (m *ModifyRequestedQuantityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Marshal(b, m, deterministic)
}
func (m *ModifyRequestedQuantityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequestedQuantityResponse.Merge(m, src)
}
func (m *ModifyRequestedQuantityResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Size(m)
}
func (m *ModifyRequestedQuantityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequestedQuantityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequestedQuantityResponse proto.InternalMessageInfo

func (m *ModifyRequestedQuantityResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// SendOrder
type SendOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrderRequest) Reset()         { *m = SendOrderRequest{} }
func (m *SendOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SendOrderRequest) ProtoMessage()    {}
func (*SendOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{8}
}

func (m *SendOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrderRequest.Unmarshal(m, b)
}
func (m *SendOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrderRequest.Marshal(b, m, deterministic)
}
func (m *SendOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrderRequest.Merge(m, src)
}
func (m *SendOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SendOrderRequest.Size(m)
}
func (m *SendOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrderRequest proto.InternalMessageInfo

func (m *SendOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SendOrderRequest) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type SendOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrderResponse) Reset()         { *m = SendOrderResponse{} }
func (m *SendOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SendOrderResponse) ProtoMessage()    {}
func (*SendOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{9}
}

func (m *SendOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrderResponse.Unmarshal(m, b)
}
func (m *SendOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrderResponse.Marshal(b, m, deterministic)
}
func (m *SendOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrderResponse.Merge(m, src)
}
func (m *SendOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SendOrderResponse.Size(m)
}
func (m *SendOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrderResponse proto.InternalMessageInfo

func (m *SendOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// ReceiveOrderItem
type ReceiveOrderItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveOrderItemRequest) Reset()         { *m = ReceiveOrderItemRequest{} }
func (m *ReceiveOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveOrderItemRequest) ProtoMessage()    {}
func (*ReceiveOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{10}
}

func (m *ReceiveOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveOrderItemRequest.Unmarshal(m, b)
}
func (m *ReceiveOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveOrderItemRequest.Merge(m, src)
}
func (m *ReceiveOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveOrderItemRequest.Size(m)
}
func (m *ReceiveOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveOrderItemRequest proto.InternalMessageInfo

func (m *ReceiveOrderItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReceiveOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ReceiveOrderItemRequest) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ReceiveOrderItemResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveOrderItemResponse) Reset()         { *m = ReceiveOrderItemResponse{} }
func (m *ReceiveOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveOrderItemResponse) ProtoMessage()    {}
func (*ReceiveOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{11}
}

func (m *ReceiveOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveOrderItemResponse.Unmarshal(m, b)
}
func (m *ReceiveOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveOrderItemResponse.Merge(m, src)
}
func (m *ReceiveOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveOrderItemResponse.Size(m)
}
func (m *ReceiveOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveOrderItemResponse proto.InternalMessageInfo

func (m *ReceiveOrderItemResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// An Order
type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              *Project `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Items                []*Item  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Date                 int32    `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Comments             string   `protobuf:"bytes,6,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{12}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *Order) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type Project struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{13}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// An order item
type Item struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	QuantityRequested    uint32   `protobuf:"varint,2,opt,name=quantity_requested,json=quantityRequested,proto3" json:"quantity_requested,omitempty"`
	QuantityReceived     uint32   `protobuf:"varint,3,opt,name=quantity_received,json=quantityReceived,proto3" json:"quantity_received,omitempty"`
	QuantityRemaining    uint32   `protobuf:"varint,4,opt,name=quantity_remaining,json=quantityRemaining,proto3" json:"quantity_remaining,omitempty"`
	ItemStatus           string   `protobuf:"bytes,5,opt,name=item_status,json=itemStatus,proto3" json:"item_status,omitempty"`
	Deleted              bool     `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{14}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Item) GetQuantityRequested() uint32 {
	if m != nil {
		return m.QuantityRequested
	}
	return 0
}

func (m *Item) GetQuantityReceived() uint32 {
	if m != nil {
		return m.QuantityReceived
	}
	return 0
}

func (m *Item) GetQuantityRemaining() uint32 {
	if m != nil {
		return m.QuantityRemaining
	}
	return 0
}

func (m *Item) GetItemStatus() string {
	if m != nil {
		return m.ItemStatus
	}
	return ""
}

func (m *Item) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// A product
type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uom                  string   `protobuf:"bytes,3,opt,name=uom,proto3" json:"uom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{15}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

// FindOrder
type FindOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOrderRequest) Reset()         { *m = FindOrderRequest{} }
func (m *FindOrderRequest) String() string { return proto.CompactTextString(m) }
func (*FindOrderRequest) ProtoMessage()    {}
func (*FindOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{16}
}

func (m *FindOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOrderRequest.Unmarshal(m, b)
}
func (m *FindOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOrderRequest.Marshal(b, m, deterministic)
}
func (m *FindOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOrderRequest.Merge(m, src)
}
func (m *FindOrderRequest) XXX_Size() int {
	return xxx_messageInfo_FindOrderRequest.Size(m)
}
func (m *FindOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOrderRequest proto.InternalMessageInfo

func (m *FindOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOrderResponse) Reset()         { *m = FindOrderResponse{} }
func (m *FindOrderResponse) String() string { return proto.CompactTextString(m) }
func (*FindOrderResponse) ProtoMessage()    {}
func (*FindOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{17}
}

func (m *FindOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOrderResponse.Unmarshal(m, b)
}
func (m *FindOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOrderResponse.Marshal(b, m, deterministic)
}
func (m *FindOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOrderResponse.Merge(m, src)
}
func (m *FindOrderResponse) XXX_Size() int {
	return xxx_messageInfo_FindOrderResponse.Size(m)
}
func (m *FindOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindOrderResponse proto.InternalMessageInfo

func (m *FindOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// Project order summary
type OrderSummary struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 int32    `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderSummary) Reset()         { *m = OrderSummary{} }
func (m *OrderSummary) String() string { return proto.CompactTextString(m) }
func (*OrderSummary) ProtoMessage()    {}
func (*OrderSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{18}
}

func (m *OrderSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSummary.Unmarshal(m, b)
}
func (m *OrderSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSummary.Marshal(b, m, deterministic)
}
func (m *OrderSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSummary.Merge(m, src)
}
func (m *OrderSummary) XXX_Size() int {
	return xxx_messageInfo_OrderSummary.Size(m)
}
func (m *OrderSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSummary.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSummary proto.InternalMessageInfo

func (m *OrderSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderSummary) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *OrderSummary) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// FindProjectOrderDates
type FindProjectOrderDatesRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindProjectOrderDatesRequest) Reset()         { *m = FindProjectOrderDatesRequest{} }
func (m *FindProjectOrderDatesRequest) String() string { return proto.CompactTextString(m) }
func (*FindProjectOrderDatesRequest) ProtoMessage()    {}
func (*FindProjectOrderDatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{19}
}

func (m *FindProjectOrderDatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectOrderDatesRequest.Unmarshal(m, b)
}
func (m *FindProjectOrderDatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectOrderDatesRequest.Marshal(b, m, deterministic)
}
func (m *FindProjectOrderDatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectOrderDatesRequest.Merge(m, src)
}
func (m *FindProjectOrderDatesRequest) XXX_Size() int {
	return xxx_messageInfo_FindProjectOrderDatesRequest.Size(m)
}
func (m *FindProjectOrderDatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectOrderDatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectOrderDatesRequest proto.InternalMessageInfo

func (m *FindProjectOrderDatesRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type FindProjectOrderDatesResponse struct {
	Orders               []*OrderSummary `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FindProjectOrderDatesResponse) Reset()         { *m = FindProjectOrderDatesResponse{} }
func (m *FindProjectOrderDatesResponse) String() string { return proto.CompactTextString(m) }
func (*FindProjectOrderDatesResponse) ProtoMessage()    {}
func (*FindProjectOrderDatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{20}
}

func (m *FindProjectOrderDatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectOrderDatesResponse.Unmarshal(m, b)
}
func (m *FindProjectOrderDatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectOrderDatesResponse.Marshal(b, m, deterministic)
}
func (m *FindProjectOrderDatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectOrderDatesResponse.Merge(m, src)
}
func (m *FindProjectOrderDatesResponse) XXX_Size() int {
	return xxx_messageInfo_FindProjectOrderDatesResponse.Size(m)
}
func (m *FindProjectOrderDatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectOrderDatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectOrderDatesResponse proto.InternalMessageInfo

func (m *FindProjectOrderDatesResponse) GetOrders() []*OrderSummary {
	if m != nil {
		return m.Orders
	}
	return nil
}

// Delete an order
type DeleteOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderRequest) Reset()         { *m = DeleteOrderRequest{} }
func (m *DeleteOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderRequest) ProtoMessage()    {}
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{21}
}

func (m *DeleteOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderRequest.Unmarshal(m, b)
}
func (m *DeleteOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderRequest.Merge(m, src)
}
func (m *DeleteOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderRequest.Size(m)
}
func (m *DeleteOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderRequest proto.InternalMessageInfo

func (m *DeleteOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type DeleteOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderResponse) Reset()         { *m = DeleteOrderResponse{} }
func (m *DeleteOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderResponse) ProtoMessage()    {}
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{22}
}

func (m *DeleteOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderResponse.Unmarshal(m, b)
}
func (m *DeleteOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderResponse.Marshal(b, m, deterministic)
}
func (m *DeleteOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderResponse.Merge(m, src)
}
func (m *DeleteOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderResponse.Size(m)
}
func (m *DeleteOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderResponse proto.InternalMessageInfo

// A result
type Result struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Indexes              []int32  `protobuf:"varint,2,rep,packed,name=indexes,proto3" json:"indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{23}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Result) GetIndexes() []int32 {
	if m != nil {
		return m.Indexes
	}
	return nil
}

// ProductSearch
type ProductSearchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSearchRequest) Reset()         { *m = ProductSearchRequest{} }
func (m *ProductSearchRequest) String() string { return proto.CompactTextString(m) }
func (*ProductSearchRequest) ProtoMessage()    {}
func (*ProductSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{24}
}

func (m *ProductSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSearchRequest.Unmarshal(m, b)
}
func (m *ProductSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSearchRequest.Marshal(b, m, deterministic)
}
func (m *ProductSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSearchRequest.Merge(m, src)
}
func (m *ProductSearchRequest) XXX_Size() int {
	return xxx_messageInfo_ProductSearchRequest.Size(m)
}
func (m *ProductSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSearchRequest proto.InternalMessageInfo

func (m *ProductSearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProductSearchResponse struct {
	Results              []*Result `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProductSearchResponse) Reset()         { *m = ProductSearchResponse{} }
func (m *ProductSearchResponse) String() string { return proto.CompactTextString(m) }
func (*ProductSearchResponse) ProtoMessage()    {}
func (*ProductSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{25}
}

func (m *ProductSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSearchResponse.Unmarshal(m, b)
}
func (m *ProductSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSearchResponse.Marshal(b, m, deterministic)
}
func (m *ProductSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSearchResponse.Merge(m, src)
}
func (m *ProductSearchResponse) XXX_Size() int {
	return xxx_messageInfo_ProductSearchResponse.Size(m)
}
func (m *ProductSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSearchResponse proto.InternalMessageInfo

func (m *ProductSearchResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

// Create a project
type CreateProjectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{26}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{27}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

// Close a project
type CloseProjectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseProjectRequest) Reset()         { *m = CloseProjectRequest{} }
func (m *CloseProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CloseProjectRequest) ProtoMessage()    {}
func (*CloseProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{28}
}

func (m *CloseProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseProjectRequest.Unmarshal(m, b)
}
func (m *CloseProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseProjectRequest.Marshal(b, m, deterministic)
}
func (m *CloseProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseProjectRequest.Merge(m, src)
}
func (m *CloseProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CloseProjectRequest.Size(m)
}
func (m *CloseProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseProjectRequest proto.InternalMessageInfo

func (m *CloseProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CloseProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseProjectResponse) Reset()         { *m = CloseProjectResponse{} }
func (m *CloseProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CloseProjectResponse) ProtoMessage()    {}
func (*CloseProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{29}
}

func (m *CloseProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseProjectResponse.Unmarshal(m, b)
}
func (m *CloseProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseProjectResponse.Marshal(b, m, deterministic)
}
func (m *CloseProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseProjectResponse.Merge(m, src)
}
func (m *CloseProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CloseProjectResponse.Size(m)
}
func (m *CloseProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseProjectResponse proto.InternalMessageInfo

// Find all projects by foreman
type FindProjectsRequest struct {
	ForemanId            string   `protobuf:"bytes,1,opt,name=foreman_id,json=foremanId,proto3" json:"foreman_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindProjectsRequest) Reset()         { *m = FindProjectsRequest{} }
func (m *FindProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*FindProjectsRequest) ProtoMessage()    {}
func (*FindProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{30}
}

func (m *FindProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectsRequest.Unmarshal(m, b)
}
func (m *FindProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectsRequest.Marshal(b, m, deterministic)
}
func (m *FindProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectsRequest.Merge(m, src)
}
func (m *FindProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_FindProjectsRequest.Size(m)
}
func (m *FindProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectsRequest proto.InternalMessageInfo

func (m *FindProjectsRequest) GetForemanId() string {
	if m != nil {
		return m.ForemanId
	}
	return ""
}

type FindProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindProjectsResponse) Reset()         { *m = FindProjectsResponse{} }
func (m *FindProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*FindProjectsResponse) ProtoMessage()    {}
func (*FindProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{31}
}

func (m *FindProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectsResponse.Unmarshal(m, b)
}
func (m *FindProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectsResponse.Marshal(b, m, deterministic)
}
func (m *FindProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectsResponse.Merge(m, src)
}
func (m *FindProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_FindProjectsResponse.Size(m)
}
func (m *FindProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectsResponse proto.InternalMessageInfo

func (m *FindProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "server.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "server.CreateOrderResponse")
	proto.RegisterType((*AddOrderItemRequest)(nil), "server.AddOrderItemRequest")
	proto.RegisterType((*AddOrderItemResponse)(nil), "server.AddOrderItemResponse")
	proto.RegisterType((*RemoveOrderItemRequest)(nil), "server.RemoveOrderItemRequest")
	proto.RegisterType((*RemoveOrderItemResponse)(nil), "server.RemoveOrderItemResponse")
	proto.RegisterType((*ModifyRequestedQuantityRequest)(nil), "server.ModifyRequestedQuantityRequest")
	proto.RegisterType((*ModifyRequestedQuantityResponse)(nil), "server.ModifyRequestedQuantityResponse")
	proto.RegisterType((*SendOrderRequest)(nil), "server.SendOrderRequest")
	proto.RegisterType((*SendOrderResponse)(nil), "server.SendOrderResponse")
	proto.RegisterType((*ReceiveOrderItemRequest)(nil), "server.ReceiveOrderItemRequest")
	proto.RegisterType((*ReceiveOrderItemResponse)(nil), "server.ReceiveOrderItemResponse")
	proto.RegisterType((*Order)(nil), "server.Order")
	proto.RegisterType((*Project)(nil), "server.Project")
	proto.RegisterType((*Item)(nil), "server.Item")
	proto.RegisterType((*Product)(nil), "server.Product")
	proto.RegisterType((*FindOrderRequest)(nil), "server.FindOrderRequest")
	proto.RegisterType((*FindOrderResponse)(nil), "server.FindOrderResponse")
	proto.RegisterType((*OrderSummary)(nil), "server.OrderSummary")
	proto.RegisterType((*FindProjectOrderDatesRequest)(nil), "server.FindProjectOrderDatesRequest")
	proto.RegisterType((*FindProjectOrderDatesResponse)(nil), "server.FindProjectOrderDatesResponse")
	proto.RegisterType((*DeleteOrderRequest)(nil), "server.DeleteOrderRequest")
	proto.RegisterType((*DeleteOrderResponse)(nil), "server.DeleteOrderResponse")
	proto.RegisterType((*Result)(nil), "server.Result")
	proto.RegisterType((*ProductSearchRequest)(nil), "server.ProductSearchRequest")
	proto.RegisterType((*ProductSearchResponse)(nil), "server.ProductSearchResponse")
	proto.RegisterType((*CreateProjectRequest)(nil), "server.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "server.CreateProjectResponse")
	proto.RegisterType((*CloseProjectRequest)(nil), "server.CloseProjectRequest")
	proto.RegisterType((*CloseProjectResponse)(nil), "server.CloseProjectResponse")
	proto.RegisterType((*FindProjectsRequest)(nil), "server.FindProjectsRequest")
	proto.RegisterType((*FindProjectsResponse)(nil), "server.FindProjectsResponse")
}

func init() { proto.RegisterFile("supply.proto", fileDescriptor_ec03c29a5b47d604) }

var fileDescriptor_ec03c29a5b47d604 = []byte{
	// 1000 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5b, 0x73, 0xdc, 0x34,
	0x14, 0xae, 0x77, 0xb3, 0xb7, 0xb3, 0xd9, 0x76, 0xa3, 0xdd, 0x24, 0xae, 0x49, 0x9a, 0x8c, 0xa0,
	0xb0, 0xb4, 0x34, 0xcc, 0x04, 0x1e, 0x18, 0x18, 0x5a, 0x42, 0x3a, 0x81, 0xc0, 0xa4, 0x80, 0x97,
	0x19, 0x1e, 0x33, 0x26, 0x52, 0xc1, 0x65, 0x6d, 0x6f, 0x7c, 0x29, 0xec, 0x5f, 0xe2, 0x81, 0xbf,
	0xc7, 0x2b, 0x23, 0x59, 0xb2, 0x25, 0x5b, 0x4e, 0xd8, 0xf6, 0xcd, 0xd2, 0xb9, 0x7d, 0x3a, 0xfa,
	0xf4, 0x49, 0x86, 0xcd, 0x24, 0x5b, 0x2e, 0x17, 0xab, 0xa3, 0x65, 0x1c, 0xa5, 0x11, 0xea, 0x26,
	0x34, 0x7e, 0x4d, 0x63, 0xfc, 0x27, 0xa0, 0xd3, 0x98, 0x7a, 0x29, 0xfd, 0x21, 0x26, 0x34, 0x76,
	0xe9, 0x75, 0x46, 0x93, 0x14, 0xed, 0x03, 0x2c, 0xe3, 0xe8, 0x15, 0xbd, 0x4a, 0x2f, 0x7d, 0x62,
	0xb7, 0x0e, 0xad, 0xd9, 0xc0, 0x1d, 0x88, 0x99, 0x73, 0x82, 0x10, 0x6c, 0x84, 0x5e, 0x40, 0xed,
	0x36, 0x37, 0xf0, 0x6f, 0x64, 0x43, 0xef, 0x65, 0x14, 0xd3, 0xc0, 0x0b, 0xed, 0x0d, 0x3e, 0x2d,
	0x87, 0x68, 0x0a, 0x1d, 0x1a, 0x78, 0xfe, 0xc2, 0xee, 0xf0, 0xf9, 0x7c, 0x80, 0x4f, 0x60, 0xa2,
	0x15, 0x4e, 0x96, 0x51, 0x98, 0x50, 0xf4, 0x08, 0x3a, 0x11, 0x9b, 0xb0, 0xad, 0x43, 0x6b, 0x36,
	0x3c, 0x9e, 0x1e, 0xe5, 0x38, 0x8f, 0xb8, 0xd7, 0x3c, 0x0b, 0x02, 0x2f, 0x5e, 0xb9, 0xb9, 0x0b,
	0x7e, 0x05, 0x93, 0x13, 0x42, 0xb8, 0xe5, 0x3c, 0xa5, 0x81, 0x04, 0x7f, 0x17, 0x5a, 0x3e, 0xe1,
	0xf1, 0x03, 0xb7, 0xe5, 0x13, 0xb1, 0x18, 0x92, 0x55, 0x17, 0xc3, 0x66, 0x1a, 0x16, 0x33, 0x86,
	0x76, 0x16, 0x05, 0x62, 0x21, 0xec, 0x13, 0x7f, 0x01, 0x53, 0xbd, 0x96, 0xc0, 0xfb, 0xae, 0x8e,
	0x77, 0xa4, 0xe1, 0x95, 0x40, 0xbf, 0x81, 0x1d, 0x97, 0x06, 0xd1, 0x6b, 0xfa, 0x96, 0x58, 0xf1,
	0x53, 0xd8, 0xad, 0x25, 0x5a, 0x07, 0xc8, 0x1f, 0xf0, 0xe0, 0x22, 0x22, 0xfe, 0xcb, 0x95, 0xa8,
	0x4f, 0xc9, 0x4f, 0x99, 0x17, 0xa6, 0x7e, 0xba, 0x7a, 0xc3, 0xe6, 0x39, 0xd0, 0xbf, 0x16, 0x19,
	0x78, 0x03, 0x47, 0x6e, 0x31, 0xc6, 0x67, 0x70, 0xd0, 0x58, 0x6c, 0x1d, 0xd0, 0x4f, 0x61, 0x3c,
	0xa7, 0x21, 0xd1, 0x08, 0x5a, 0x85, 0xe9, 0x40, 0xff, 0x2a, 0x0a, 0x02, 0x1a, 0xa6, 0x89, 0x00,
	0x59, 0x8c, 0xf1, 0x67, 0xb0, 0xa5, 0xc4, 0xaf, 0x53, 0x99, 0xb0, 0x76, 0x5f, 0x51, 0xff, 0xad,
	0x37, 0xee, 0xc6, 0x3e, 0x3d, 0x03, 0xbb, 0x5e, 0x65, 0x1d, 0x98, 0xff, 0x58, 0xd0, 0xe1, 0x13,
	0x35, 0x54, 0x1f, 0x42, 0x4f, 0x9c, 0x5a, 0x0e, 0x69, 0x78, 0x7c, 0x4f, 0x26, 0xf8, 0x31, 0x9f,
	0x76, 0xa5, 0x1d, 0x61, 0xe8, 0xf8, 0x29, 0x0d, 0x12, 0xbb, 0x7d, 0xd8, 0x9e, 0x0d, 0x8f, 0x37,
	0xa5, 0x23, 0x87, 0x93, 0x9b, 0xd8, 0x51, 0x21, 0x5e, 0x4a, 0xf9, 0xb9, 0xe8, 0xb8, 0xfc, 0x1b,
	0xed, 0x40, 0x37, 0x49, 0xbd, 0x34, 0x4b, 0xc4, 0xf1, 0x16, 0x23, 0x6d, 0x47, 0xba, 0x95, 0x1d,
	0x79, 0x02, 0x3d, 0x51, 0xbf, 0x86, 0x58, 0x9e, 0xc6, 0x56, 0x79, 0x1a, 0xf1, 0xbf, 0x16, 0x6c,
	0x30, 0x18, 0x62, 0x39, 0xac, 0xa5, 0xa2, 0x1f, 0xea, 0x72, 0xd8, 0xb4, 0x2b, 0xed, 0xe8, 0x09,
	0x20, 0xd9, 0xe0, 0xcb, 0x58, 0xf2, 0x8f, 0x67, 0x1d, 0xb9, 0x5b, 0xd7, 0x3a, 0xe9, 0x29, 0x41,
	0x8f, 0x61, 0x4b, 0x71, 0xe7, 0x9b, 0x41, 0xc4, 0x46, 0x8d, 0x4b, 0xef, 0x7c, 0xbe, 0x92, 0x3b,
	0xf0, 0xfc, 0xd0, 0x0f, 0x7f, 0xe3, 0x4d, 0xd1, 0x72, 0x0b, 0x03, 0x3a, 0x80, 0x21, 0x6b, 0xdf,
	0xa5, 0xd6, 0x26, 0x60, 0x53, 0xf3, 0xbc, 0x55, 0x36, 0xf4, 0x08, 0x5d, 0x50, 0x06, 0x90, 0x75,
	0xaa, 0xef, 0xca, 0x21, 0x7e, 0xc6, 0x1b, 0xc5, 0x17, 0xf4, 0x3f, 0x1a, 0x25, 0x65, 0xab, 0x5d,
	0xca, 0x16, 0x86, 0xf1, 0x99, 0x7f, 0xf3, 0xd9, 0x61, 0xe7, 0x43, 0xf1, 0x59, 0x87, 0x78, 0xdf,
	0xc1, 0xa6, 0xaa, 0xcb, 0x26, 0x8c, 0x9c, 0x2f, 0x2d, 0x23, 0x5f, 0xda, 0x2a, 0x5f, 0xf0, 0x97,
	0xb0, 0xc7, 0x50, 0x08, 0x5e, 0xf0, 0xb4, 0xcf, 0xbd, 0x94, 0x26, 0xe6, 0x2b, 0xc9, 0xaa, 0x5c,
	0x49, 0xf8, 0x02, 0xf6, 0x1b, 0xc2, 0xc5, 0x82, 0x3e, 0x82, 0x2e, 0x07, 0x9d, 0xd8, 0x16, 0x27,
	0xb8, 0xf9, 0x66, 0x11, 0x3e, 0xf8, 0x63, 0x40, 0xcf, 0xf9, 0x1e, 0x68, 0x9d, 0xbb, 0x0f, 0x7d,
	0x6e, 0x2f, 0x11, 0xf4, 0xf8, 0xf8, 0x9c, 0xe0, 0x6d, 0x98, 0x68, 0x01, 0x79, 0x55, 0x7c, 0x01,
	0x5d, 0x97, 0x26, 0xd9, 0x22, 0x5d, 0x87, 0xbb, 0x36, 0xf4, 0xfc, 0x90, 0xd0, 0xbf, 0x28, 0xd3,
	0xb2, 0xf6, 0xac, 0xe3, 0xca, 0x21, 0x7e, 0x04, 0x53, 0xe1, 0x3d, 0xa7, 0x5e, 0x7c, 0xf5, 0xbb,
	0x04, 0x26, 0xc9, 0x60, 0x29, 0xa7, 0xe6, 0x04, 0xb6, 0x2b, 0xbe, 0xa2, 0x13, 0x33, 0xe8, 0xc5,
	0x1c, 0x13, 0xe3, 0x22, 0x6b, 0xc5, 0x5d, 0x89, 0x24, 0x87, 0xea, 0x4a, 0x33, 0xfe, 0x1c, 0xa6,
	0xf9, 0x1d, 0x2d, 0xd5, 0xa2, 0x41, 0xfc, 0x4c, 0x87, 0x76, 0x17, 0xb6, 0x2b, 0xb1, 0xa2, 0x25,
	0x0f, 0x61, 0x72, 0xba, 0x88, 0x92, 0x5b, 0x72, 0xe2, 0x1d, 0x98, 0xea, 0x6e, 0x22, 0xfc, 0x53,
	0x98, 0x28, 0x1b, 0xad, 0xd2, 0x43, 0xbc, 0x37, 0x14, 0x7a, 0x88, 0x99, 0x73, 0x82, 0x4f, 0x61,
	0xaa, 0x47, 0x89, 0x5e, 0x3c, 0x86, 0xbe, 0xe0, 0x90, 0xe4, 0x45, 0x4d, 0x21, 0x0b, 0x87, 0xe3,
	0xbf, 0xfb, 0xd0, 0x9d, 0xf3, 0x47, 0x14, 0xfa, 0x16, 0x86, 0xca, 0xeb, 0x05, 0x39, 0x32, 0xa8,
	0xfe, 0x96, 0x72, 0xde, 0x31, 0xda, 0xc4, 0x6a, 0xee, 0xa0, 0xaf, 0x61, 0x50, 0xdc, 0x4e, 0xc8,
	0x96, 0xbe, 0xd5, 0x0b, 0xcf, 0xb9, 0x6f, 0xb0, 0x14, 0x39, 0xbe, 0x87, 0x4d, 0xf5, 0x71, 0x82,
	0x8a, 0x92, 0x86, 0xe7, 0x91, 0xb3, 0x67, 0x36, 0x16, 0xc9, 0x7e, 0x86, 0x7b, 0x95, 0x37, 0x06,
	0x7a, 0x50, 0x12, 0xc4, 0xf4, 0x8a, 0x71, 0x0e, 0x1a, 0xed, 0x45, 0xd6, 0x5f, 0x60, 0x5c, 0xbd,
	0xe4, 0x90, 0x12, 0x66, 0xbc, 0x64, 0x9d, 0xc3, 0x66, 0x87, 0x22, 0xf1, 0x02, 0x76, 0x1b, 0x5e,
	0x19, 0xe8, 0x7d, 0x19, 0x7e, 0xf3, 0x9b, 0xc7, 0xf9, 0xe0, 0x56, 0xbf, 0xa2, 0xda, 0x57, 0x30,
	0x28, 0xb4, 0xb2, 0xdc, 0xad, 0xaa, 0xc4, 0x96, 0xbb, 0x55, 0x17, 0x56, 0x02, 0xdb, 0x46, 0xa1,
	0x42, 0xef, 0xa9, 0x31, 0x4d, 0x32, 0xe8, 0x3c, 0xbc, 0xc5, 0x4b, 0x54, 0x39, 0x83, 0xa1, 0x22,
	0x47, 0x25, 0x3f, 0xeb, 0xa2, 0x56, 0xf2, 0xd3, 0xa0, 0x5f, 0xe8, 0x05, 0x8c, 0x34, 0x11, 0x41,
	0x7b, 0x15, 0xd5, 0xd2, 0x74, 0xc8, 0xd9, 0x6f, 0xb0, 0x16, 0xfd, 0x7b, 0x01, 0x23, 0x4d, 0x15,
	0xca, 0x7c, 0x26, 0xa1, 0x29, 0xf3, 0x99, 0xa5, 0x84, 0x33, 0x5f, 0x55, 0x89, 0x92, 0xf9, 0x06,
	0x89, 0x29, 0x99, 0x6f, 0x14, 0x16, 0x9e, 0x4c, 0x15, 0x89, 0x32, 0x99, 0x41, 0x70, 0xca, 0x64,
	0x26, 0x5d, 0xc1, 0x77, 0x7e, 0xed, 0xf2, 0xff, 0xac, 0x4f, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xce, 0x11, 0xc3, 0x1a, 0x77, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SupplyClient is the client API for Supply service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SupplyClient interface {
	// Ordering
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	SendOrder(ctx context.Context, in *SendOrderRequest, opts ...grpc.CallOption) (*SendOrderResponse, error)
	AddOrderItem(ctx context.Context, in *AddOrderItemRequest, opts ...grpc.CallOption) (*AddOrderItemResponse, error)
	RemoveOrderItem(ctx context.Context, in *RemoveOrderItemRequest, opts ...grpc.CallOption) (*RemoveOrderItemResponse, error)
	ReceiveOrderItem(ctx context.Context, in *ReceiveOrderItemRequest, opts ...grpc.CallOption) (*ReceiveOrderItemResponse, error)
	ModifyRequestedQuantity(ctx context.Context, in *ModifyRequestedQuantityRequest, opts ...grpc.CallOption) (*ModifyRequestedQuantityResponse, error)
	FindOrder(ctx context.Context, in *FindOrderRequest, opts ...grpc.CallOption) (*FindOrderResponse, error)
	FindProjectOrderDates(ctx context.Context, in *FindProjectOrderDatesRequest, opts ...grpc.CallOption) (*FindProjectOrderDatesResponse, error)
	DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*DeleteOrderResponse, error)
	// ProductSearch
	ProductSearch(ctx context.Context, in *ProductSearchRequest, opts ...grpc.CallOption) (*ProductSearchResponse, error)
	// Projects
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	CloseProject(ctx context.Context, in *CloseProjectRequest, opts ...grpc.CallOption) (*CloseProjectResponse, error)
	FindProjects(ctx context.Context, in *FindProjectsRequest, opts ...grpc.CallOption) (*FindProjectsResponse, error)
}

type supplyClient struct {
	cc *grpc.ClientConn
}

func NewSupplyClient(cc *grpc.ClientConn) SupplyClient {
	return &supplyClient{cc}
}

func (c *supplyClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) SendOrder(ctx context.Context, in *SendOrderRequest, opts ...grpc.CallOption) (*SendOrderResponse, error) {
	out := new(SendOrderResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/SendOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) AddOrderItem(ctx context.Context, in *AddOrderItemRequest, opts ...grpc.CallOption) (*AddOrderItemResponse, error) {
	out := new(AddOrderItemResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/AddOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) RemoveOrderItem(ctx context.Context, in *RemoveOrderItemRequest, opts ...grpc.CallOption) (*RemoveOrderItemResponse, error) {
	out := new(RemoveOrderItemResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/RemoveOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) ReceiveOrderItem(ctx context.Context, in *ReceiveOrderItemRequest, opts ...grpc.CallOption) (*ReceiveOrderItemResponse, error) {
	out := new(ReceiveOrderItemResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/ReceiveOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) ModifyRequestedQuantity(ctx context.Context, in *ModifyRequestedQuantityRequest, opts ...grpc.CallOption) (*ModifyRequestedQuantityResponse, error) {
	out := new(ModifyRequestedQuantityResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/ModifyRequestedQuantity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) FindOrder(ctx context.Context, in *FindOrderRequest, opts ...grpc.CallOption) (*FindOrderResponse, error) {
	out := new(FindOrderResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/FindOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) FindProjectOrderDates(ctx context.Context, in *FindProjectOrderDatesRequest, opts ...grpc.CallOption) (*FindProjectOrderDatesResponse, error) {
	out := new(FindProjectOrderDatesResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/FindProjectOrderDates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*DeleteOrderResponse, error) {
	out := new(DeleteOrderResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/DeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) ProductSearch(ctx context.Context, in *ProductSearchRequest, opts ...grpc.CallOption) (*ProductSearchResponse, error) {
	out := new(ProductSearchResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/ProductSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) CloseProject(ctx context.Context, in *CloseProjectRequest, opts ...grpc.CallOption) (*CloseProjectResponse, error) {
	out := new(CloseProjectResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/CloseProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) FindProjects(ctx context.Context, in *FindProjectsRequest, opts ...grpc.CallOption) (*FindProjectsResponse, error) {
	out := new(FindProjectsResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/FindProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupplyServer is the server API for Supply service.
type SupplyServer interface {
	// Ordering
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	SendOrder(context.Context, *SendOrderRequest) (*SendOrderResponse, error)
	AddOrderItem(context.Context, *AddOrderItemRequest) (*AddOrderItemResponse, error)
	RemoveOrderItem(context.Context, *RemoveOrderItemRequest) (*RemoveOrderItemResponse, error)
	ReceiveOrderItem(context.Context, *ReceiveOrderItemRequest) (*ReceiveOrderItemResponse, error)
	ModifyRequestedQuantity(context.Context, *ModifyRequestedQuantityRequest) (*ModifyRequestedQuantityResponse, error)
	FindOrder(context.Context, *FindOrderRequest) (*FindOrderResponse, error)
	FindProjectOrderDates(context.Context, *FindProjectOrderDatesRequest) (*FindProjectOrderDatesResponse, error)
	DeleteOrder(context.Context, *DeleteOrderRequest) (*DeleteOrderResponse, error)
	// ProductSearch
	ProductSearch(context.Context, *ProductSearchRequest) (*ProductSearchResponse, error)
	// Projects
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	CloseProject(context.Context, *CloseProjectRequest) (*CloseProjectResponse, error)
	FindProjects(context.Context, *FindProjectsRequest) (*FindProjectsResponse, error)
}

func RegisterSupplyServer(s *grpc.Server, srv SupplyServer) {
	s.RegisterService(&_Supply_serviceDesc, srv)
}

func _Supply_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).SendOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/SendOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).SendOrder(ctx, req.(*SendOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_AddOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).AddOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/AddOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).AddOrderItem(ctx, req.(*AddOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_RemoveOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).RemoveOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/RemoveOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).RemoveOrderItem(ctx, req.(*RemoveOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_ReceiveOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).ReceiveOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/ReceiveOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).ReceiveOrderItem(ctx, req.(*ReceiveOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_ModifyRequestedQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRequestedQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).ModifyRequestedQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/ModifyRequestedQuantity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).ModifyRequestedQuantity(ctx, req.(*ModifyRequestedQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_FindOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).FindOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/FindOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).FindOrder(ctx, req.(*FindOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_FindProjectOrderDates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindProjectOrderDatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).FindProjectOrderDates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/FindProjectOrderDates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).FindProjectOrderDates(ctx, req.(*FindProjectOrderDatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/DeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).DeleteOrder(ctx, req.(*DeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_ProductSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).ProductSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/ProductSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).ProductSearch(ctx, req.(*ProductSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_CloseProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).CloseProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/CloseProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).CloseProject(ctx, req.(*CloseProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_FindProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).FindProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/FindProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).FindProjects(ctx, req.(*FindProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Supply_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Supply",
	HandlerType: (*SupplyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Supply_CreateOrder_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _Supply_SendOrder_Handler,
		},
		{
			MethodName: "AddOrderItem",
			Handler:    _Supply_AddOrderItem_Handler,
		},
		{
			MethodName: "RemoveOrderItem",
			Handler:    _Supply_RemoveOrderItem_Handler,
		},
		{
			MethodName: "ReceiveOrderItem",
			Handler:    _Supply_ReceiveOrderItem_Handler,
		},
		{
			MethodName: "ModifyRequestedQuantity",
			Handler:    _Supply_ModifyRequestedQuantity_Handler,
		},
		{
			MethodName: "FindOrder",
			Handler:    _Supply_FindOrder_Handler,
		},
		{
			MethodName: "FindProjectOrderDates",
			Handler:    _Supply_FindProjectOrderDates_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _Supply_DeleteOrder_Handler,
		},
		{
			MethodName: "ProductSearch",
			Handler:    _Supply_ProductSearch_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _Supply_CreateProject_Handler,
		},
		{
			MethodName: "CloseProject",
			Handler:    _Supply_CloseProject_Handler,
		},
		{
			MethodName: "FindProjects",
			Handler:    _Supply_FindProjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supply.proto",
}
