// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supply.proto

package server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CreateOrder
type CreateOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOrderRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type CreateOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{1}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

// AddOrderItem
type AddOrderItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uom                  string   `protobuf:"bytes,4,opt,name=uom,proto3" json:"uom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderItemRequest) Reset()         { *m = AddOrderItemRequest{} }
func (m *AddOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddOrderItemRequest) ProtoMessage()    {}
func (*AddOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{2}
}

func (m *AddOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderItemRequest.Unmarshal(m, b)
}
func (m *AddOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *AddOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderItemRequest.Merge(m, src)
}
func (m *AddOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddOrderItemRequest.Size(m)
}
func (m *AddOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderItemRequest proto.InternalMessageInfo

func (m *AddOrderItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *AddOrderItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddOrderItemRequest) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

type AddOrderItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderItemResponse) Reset()         { *m = AddOrderItemResponse{} }
func (m *AddOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddOrderItemResponse) ProtoMessage()    {}
func (*AddOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{3}
}

func (m *AddOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderItemResponse.Unmarshal(m, b)
}
func (m *AddOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *AddOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderItemResponse.Merge(m, src)
}
func (m *AddOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddOrderItemResponse.Size(m)
}
func (m *AddOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderItemResponse proto.InternalMessageInfo

// RemoveOrderItem
type RemoveOrderItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrderItemRequest) Reset()         { *m = RemoveOrderItemRequest{} }
func (m *RemoveOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveOrderItemRequest) ProtoMessage()    {}
func (*RemoveOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{4}
}

func (m *RemoveOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrderItemRequest.Unmarshal(m, b)
}
func (m *RemoveOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *RemoveOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrderItemRequest.Merge(m, src)
}
func (m *RemoveOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveOrderItemRequest.Size(m)
}
func (m *RemoveOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrderItemRequest proto.InternalMessageInfo

func (m *RemoveOrderItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoveOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type RemoveOrderItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrderItemResponse) Reset()         { *m = RemoveOrderItemResponse{} }
func (m *RemoveOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveOrderItemResponse) ProtoMessage()    {}
func (*RemoveOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{5}
}

func (m *RemoveOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrderItemResponse.Unmarshal(m, b)
}
func (m *RemoveOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *RemoveOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrderItemResponse.Merge(m, src)
}
func (m *RemoveOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveOrderItemResponse.Size(m)
}
func (m *RemoveOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrderItemResponse proto.InternalMessageInfo

// ModifyRequestedQuantity
type ModifyRequestedQuantityRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequestedQuantityRequest) Reset()         { *m = ModifyRequestedQuantityRequest{} }
func (m *ModifyRequestedQuantityRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRequestedQuantityRequest) ProtoMessage()    {}
func (*ModifyRequestedQuantityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{6}
}

func (m *ModifyRequestedQuantityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Unmarshal(m, b)
}
func (m *ModifyRequestedQuantityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Marshal(b, m, deterministic)
}
func (m *ModifyRequestedQuantityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequestedQuantityRequest.Merge(m, src)
}
func (m *ModifyRequestedQuantityRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Size(m)
}
func (m *ModifyRequestedQuantityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequestedQuantityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequestedQuantityRequest proto.InternalMessageInfo

func (m *ModifyRequestedQuantityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ModifyRequestedQuantityRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ModifyRequestedQuantityRequest) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ModifyRequestedQuantityResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequestedQuantityResponse) Reset()         { *m = ModifyRequestedQuantityResponse{} }
func (m *ModifyRequestedQuantityResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyRequestedQuantityResponse) ProtoMessage()    {}
func (*ModifyRequestedQuantityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{7}
}

func (m *ModifyRequestedQuantityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Unmarshal(m, b)
}
func (m *ModifyRequestedQuantityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Marshal(b, m, deterministic)
}
func (m *ModifyRequestedQuantityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequestedQuantityResponse.Merge(m, src)
}
func (m *ModifyRequestedQuantityResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Size(m)
}
func (m *ModifyRequestedQuantityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequestedQuantityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequestedQuantityResponse proto.InternalMessageInfo

// SendOrder
type SendOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrderRequest) Reset()         { *m = SendOrderRequest{} }
func (m *SendOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SendOrderRequest) ProtoMessage()    {}
func (*SendOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{8}
}

func (m *SendOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrderRequest.Unmarshal(m, b)
}
func (m *SendOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrderRequest.Marshal(b, m, deterministic)
}
func (m *SendOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrderRequest.Merge(m, src)
}
func (m *SendOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SendOrderRequest.Size(m)
}
func (m *SendOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrderRequest proto.InternalMessageInfo

func (m *SendOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SendOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrderResponse) Reset()         { *m = SendOrderResponse{} }
func (m *SendOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SendOrderResponse) ProtoMessage()    {}
func (*SendOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{9}
}

func (m *SendOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrderResponse.Unmarshal(m, b)
}
func (m *SendOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrderResponse.Marshal(b, m, deterministic)
}
func (m *SendOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrderResponse.Merge(m, src)
}
func (m *SendOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SendOrderResponse.Size(m)
}
func (m *SendOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrderResponse proto.InternalMessageInfo

// ReceiveOrderItem
type ReceiveOrderItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveOrderItemRequest) Reset()         { *m = ReceiveOrderItemRequest{} }
func (m *ReceiveOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveOrderItemRequest) ProtoMessage()    {}
func (*ReceiveOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{10}
}

func (m *ReceiveOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveOrderItemRequest.Unmarshal(m, b)
}
func (m *ReceiveOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveOrderItemRequest.Merge(m, src)
}
func (m *ReceiveOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveOrderItemRequest.Size(m)
}
func (m *ReceiveOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveOrderItemRequest proto.InternalMessageInfo

func (m *ReceiveOrderItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReceiveOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ReceiveOrderItemRequest) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ReceiveOrderItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveOrderItemResponse) Reset()         { *m = ReceiveOrderItemResponse{} }
func (m *ReceiveOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveOrderItemResponse) ProtoMessage()    {}
func (*ReceiveOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{11}
}

func (m *ReceiveOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveOrderItemResponse.Unmarshal(m, b)
}
func (m *ReceiveOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveOrderItemResponse.Merge(m, src)
}
func (m *ReceiveOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveOrderItemResponse.Size(m)
}
func (m *ReceiveOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveOrderItemResponse proto.InternalMessageInfo

// FindProjectOrderDates
type FindProjectOrderDatesRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindProjectOrderDatesRequest) Reset()         { *m = FindProjectOrderDatesRequest{} }
func (m *FindProjectOrderDatesRequest) String() string { return proto.CompactTextString(m) }
func (*FindProjectOrderDatesRequest) ProtoMessage()    {}
func (*FindProjectOrderDatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{12}
}

func (m *FindProjectOrderDatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectOrderDatesRequest.Unmarshal(m, b)
}
func (m *FindProjectOrderDatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectOrderDatesRequest.Marshal(b, m, deterministic)
}
func (m *FindProjectOrderDatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectOrderDatesRequest.Merge(m, src)
}
func (m *FindProjectOrderDatesRequest) XXX_Size() int {
	return xxx_messageInfo_FindProjectOrderDatesRequest.Size(m)
}
func (m *FindProjectOrderDatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectOrderDatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectOrderDatesRequest proto.InternalMessageInfo

func (m *FindProjectOrderDatesRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type FindProjectOrderDatesResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindProjectOrderDatesResponse) Reset()         { *m = FindProjectOrderDatesResponse{} }
func (m *FindProjectOrderDatesResponse) String() string { return proto.CompactTextString(m) }
func (*FindProjectOrderDatesResponse) ProtoMessage()    {}
func (*FindProjectOrderDatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{13}
}

func (m *FindProjectOrderDatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectOrderDatesResponse.Unmarshal(m, b)
}
func (m *FindProjectOrderDatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectOrderDatesResponse.Marshal(b, m, deterministic)
}
func (m *FindProjectOrderDatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectOrderDatesResponse.Merge(m, src)
}
func (m *FindProjectOrderDatesResponse) XXX_Size() int {
	return xxx_messageInfo_FindProjectOrderDatesResponse.Size(m)
}
func (m *FindProjectOrderDatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectOrderDatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectOrderDatesResponse proto.InternalMessageInfo

func (m *FindProjectOrderDatesResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

// An order
type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 int64    `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{14}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// FindOrder
type FindOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOrderRequest) Reset()         { *m = FindOrderRequest{} }
func (m *FindOrderRequest) String() string { return proto.CompactTextString(m) }
func (*FindOrderRequest) ProtoMessage()    {}
func (*FindOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{15}
}

func (m *FindOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOrderRequest.Unmarshal(m, b)
}
func (m *FindOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOrderRequest.Marshal(b, m, deterministic)
}
func (m *FindOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOrderRequest.Merge(m, src)
}
func (m *FindOrderRequest) XXX_Size() int {
	return xxx_messageInfo_FindOrderRequest.Size(m)
}
func (m *FindOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOrderRequest proto.InternalMessageInfo

func (m *FindOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindOrderResponse struct {
	Date                 int64    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Items                []*Item  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOrderResponse) Reset()         { *m = FindOrderResponse{} }
func (m *FindOrderResponse) String() string { return proto.CompactTextString(m) }
func (*FindOrderResponse) ProtoMessage()    {}
func (*FindOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{16}
}

func (m *FindOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOrderResponse.Unmarshal(m, b)
}
func (m *FindOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOrderResponse.Marshal(b, m, deterministic)
}
func (m *FindOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOrderResponse.Merge(m, src)
}
func (m *FindOrderResponse) XXX_Size() int {
	return xxx_messageInfo_FindOrderResponse.Size(m)
}
func (m *FindOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindOrderResponse proto.InternalMessageInfo

func (m *FindOrderResponse) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *FindOrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FindOrderResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// An order item
type Item struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uom                  string   `protobuf:"bytes,3,opt,name=uom,proto3" json:"uom,omitempty"`
	QuantityRequested    uint32   `protobuf:"varint,4,opt,name=quantity_requested,json=quantityRequested,proto3" json:"quantity_requested,omitempty"`
	QuantityReceived     uint32   `protobuf:"varint,5,opt,name=quantity_received,json=quantityReceived,proto3" json:"quantity_received,omitempty"`
	ItemStatus           string   `protobuf:"bytes,6,opt,name=item_status,json=itemStatus,proto3" json:"item_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{17}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

func (m *Item) GetQuantityRequested() uint32 {
	if m != nil {
		return m.QuantityRequested
	}
	return 0
}

func (m *Item) GetQuantityReceived() uint32 {
	if m != nil {
		return m.QuantityReceived
	}
	return 0
}

func (m *Item) GetItemStatus() string {
	if m != nil {
		return m.ItemStatus
	}
	return ""
}

// ProductSearch
type ProductSearchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSearchRequest) Reset()         { *m = ProductSearchRequest{} }
func (m *ProductSearchRequest) String() string { return proto.CompactTextString(m) }
func (*ProductSearchRequest) ProtoMessage()    {}
func (*ProductSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{18}
}

func (m *ProductSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSearchRequest.Unmarshal(m, b)
}
func (m *ProductSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSearchRequest.Marshal(b, m, deterministic)
}
func (m *ProductSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSearchRequest.Merge(m, src)
}
func (m *ProductSearchRequest) XXX_Size() int {
	return xxx_messageInfo_ProductSearchRequest.Size(m)
}
func (m *ProductSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSearchRequest proto.InternalMessageInfo

func (m *ProductSearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProductSearchResponse struct {
	Results              []*Result `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProductSearchResponse) Reset()         { *m = ProductSearchResponse{} }
func (m *ProductSearchResponse) String() string { return proto.CompactTextString(m) }
func (*ProductSearchResponse) ProtoMessage()    {}
func (*ProductSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{19}
}

func (m *ProductSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSearchResponse.Unmarshal(m, b)
}
func (m *ProductSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSearchResponse.Marshal(b, m, deterministic)
}
func (m *ProductSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSearchResponse.Merge(m, src)
}
func (m *ProductSearchResponse) XXX_Size() int {
	return xxx_messageInfo_ProductSearchResponse.Size(m)
}
func (m *ProductSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSearchResponse proto.InternalMessageInfo

func (m *ProductSearchResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type Result struct {
	ProductUuid          string   `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uom                  string   `protobuf:"bytes,4,opt,name=uom,proto3" json:"uom,omitempty"`
	Indexes              []*Index `protobuf:"bytes,5,rep,name=indexes,proto3" json:"indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{20}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetProductUuid() string {
	if m != nil {
		return m.ProductUuid
	}
	return ""
}

func (m *Result) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Result) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Result) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

func (m *Result) GetIndexes() []*Index {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type Index struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec03c29a5b47d604, []int{21}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "server.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "server.CreateOrderResponse")
	proto.RegisterType((*AddOrderItemRequest)(nil), "server.AddOrderItemRequest")
	proto.RegisterType((*AddOrderItemResponse)(nil), "server.AddOrderItemResponse")
	proto.RegisterType((*RemoveOrderItemRequest)(nil), "server.RemoveOrderItemRequest")
	proto.RegisterType((*RemoveOrderItemResponse)(nil), "server.RemoveOrderItemResponse")
	proto.RegisterType((*ModifyRequestedQuantityRequest)(nil), "server.ModifyRequestedQuantityRequest")
	proto.RegisterType((*ModifyRequestedQuantityResponse)(nil), "server.ModifyRequestedQuantityResponse")
	proto.RegisterType((*SendOrderRequest)(nil), "server.SendOrderRequest")
	proto.RegisterType((*SendOrderResponse)(nil), "server.SendOrderResponse")
	proto.RegisterType((*ReceiveOrderItemRequest)(nil), "server.ReceiveOrderItemRequest")
	proto.RegisterType((*ReceiveOrderItemResponse)(nil), "server.ReceiveOrderItemResponse")
	proto.RegisterType((*FindProjectOrderDatesRequest)(nil), "server.FindProjectOrderDatesRequest")
	proto.RegisterType((*FindProjectOrderDatesResponse)(nil), "server.FindProjectOrderDatesResponse")
	proto.RegisterType((*Order)(nil), "server.Order")
	proto.RegisterType((*FindOrderRequest)(nil), "server.FindOrderRequest")
	proto.RegisterType((*FindOrderResponse)(nil), "server.FindOrderResponse")
	proto.RegisterType((*Item)(nil), "server.Item")
	proto.RegisterType((*ProductSearchRequest)(nil), "server.ProductSearchRequest")
	proto.RegisterType((*ProductSearchResponse)(nil), "server.ProductSearchResponse")
	proto.RegisterType((*Result)(nil), "server.Result")
	proto.RegisterType((*Index)(nil), "server.Index")
}

func init() { proto.RegisterFile("supply.proto", fileDescriptor_ec03c29a5b47d604) }

var fileDescriptor_ec03c29a5b47d604 = []byte{
	// 744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x52, 0xd3, 0x40,
	0x14, 0x36, 0x6d, 0x53, 0xec, 0x69, 0x8b, 0xed, 0xe1, 0x2f, 0x44, 0xca, 0xcf, 0x8e, 0x08, 0xa3,
	0x23, 0x17, 0x78, 0xed, 0x8c, 0x88, 0x83, 0x76, 0x1c, 0x15, 0x53, 0x1d, 0x2f, 0x99, 0xd8, 0x5d,
	0x21, 0x48, 0x9b, 0x92, 0x6c, 0x18, 0xfb, 0x22, 0x3e, 0x93, 0x8f, 0xe4, 0xa5, 0x93, 0xcd, 0xee,
	0x36, 0x4d, 0x93, 0xe2, 0xc8, 0xdd, 0xee, 0x77, 0xce, 0x9e, 0xff, 0xf3, 0x25, 0xd0, 0x08, 0xa3,
	0xd1, 0xe8, 0x6a, 0x7c, 0x30, 0x0a, 0x7c, 0xee, 0x63, 0x35, 0x64, 0xc1, 0x0d, 0x0b, 0xc8, 0x31,
	0xe0, 0x71, 0xc0, 0x5c, 0xce, 0x3e, 0x06, 0x94, 0x05, 0x0e, 0xbb, 0x8e, 0x58, 0xc8, 0x71, 0x11,
	0x4a, 0x1e, 0xb5, 0x8c, 0x6d, 0x63, 0xbf, 0xe6, 0x94, 0x3c, 0x8a, 0x1d, 0x80, 0x51, 0xe0, 0x5f,
	0xb2, 0x3e, 0x3f, 0xf3, 0xa8, 0x55, 0x12, 0x78, 0x4d, 0x22, 0x5d, 0x4a, 0x56, 0x60, 0x69, 0xca,
	0x48, 0x38, 0xf2, 0x87, 0x21, 0x23, 0x97, 0xb0, 0x74, 0x44, 0xa9, 0xc0, 0xba, 0x9c, 0x0d, 0xe6,
	0x1b, 0xa7, 0x51, 0xd6, 0x78, 0x8c, 0x74, 0x29, 0x22, 0x54, 0x86, 0xee, 0x80, 0x59, 0x65, 0x21,
	0x10, 0x67, 0x6c, 0x41, 0x39, 0xf2, 0x07, 0x56, 0x45, 0x40, 0xf1, 0x91, 0xac, 0xc2, 0xf2, 0xb4,
	0x2f, 0x19, 0xc3, 0x1b, 0x58, 0x75, 0xd8, 0xc0, 0xbf, 0x61, 0x77, 0x0c, 0x83, 0xac, 0xc3, 0xda,
	0x8c, 0x21, 0xe9, 0xe3, 0x07, 0x6c, 0xbe, 0xf7, 0xa9, 0xf7, 0x7d, 0x2c, 0x4d, 0x33, 0xfa, 0x29,
	0x72, 0x87, 0xdc, 0xe3, 0xe3, 0xff, 0x4c, 0xd9, 0x86, 0xfb, 0xd7, 0xd2, 0x82, 0x48, 0xbb, 0xe9,
	0xe8, 0x3b, 0xd9, 0x81, 0xad, 0x42, 0x67, 0x32, 0x1e, 0x02, 0xad, 0x1e, 0x1b, 0xd2, 0x79, 0x1d,
	0x25, 0x4b, 0xd0, 0x4e, 0xe9, 0xc8, 0x87, 0x34, 0xce, 0xb1, 0xcf, 0xbc, 0x3b, 0x57, 0x6b, 0x6e,
	0x06, 0x36, 0x58, 0xb3, 0x5e, 0x64, 0x04, 0x2f, 0x60, 0xe3, 0xc4, 0x1b, 0xd2, 0xd3, 0x64, 0xb4,
	0x84, 0xfc, 0xb5, 0xcb, 0x59, 0xa8, 0xc2, 0x98, 0x1e, 0x44, 0x23, 0x3b, 0x88, 0x27, 0xd0, 0x29,
	0x78, 0x9e, 0xd8, 0xc7, 0x5d, 0xa8, 0xfa, 0x31, 0x1a, 0x5a, 0xc6, 0x76, 0x79, 0xbf, 0x7e, 0xd8,
	0x3c, 0x48, 0xf6, 0xe0, 0x20, 0x29, 0x84, 0x14, 0x92, 0x63, 0x30, 0x05, 0x30, 0x93, 0x36, 0x42,
	0x85, 0xba, 0x9c, 0x89, 0x84, 0xcb, 0x8e, 0x38, 0xe3, 0x2a, 0x54, 0x43, 0xee, 0xf2, 0x28, 0x94,
	0x23, 0x2a, 0x6f, 0x71, 0x1b, 0xe2, 0x60, 0xe6, 0xb6, 0xa1, 0x0f, 0xed, 0x94, 0x8e, 0x0c, 0x52,
	0x39, 0x31, 0x72, 0x9d, 0x94, 0xd2, 0x4e, 0x90, 0x80, 0xe9, 0x71, 0x36, 0x88, 0x7d, 0xc7, 0xf9,
	0x34, 0x54, 0x3e, 0xa2, 0xaa, 0x89, 0x88, 0xfc, 0x36, 0xa0, 0x12, 0xdf, 0x33, 0x4d, 0x33, 0x8a,
	0x36, 0xad, 0x34, 0xbb, 0x69, 0x65, 0xbd, 0x69, 0xf8, 0x0c, 0x50, 0xb5, 0xf2, 0x2c, 0x50, 0x33,
	0x28, 0x56, 0xb1, 0xe9, 0xb4, 0xaf, 0xa7, 0x07, 0x9f, 0x51, 0x7c, 0x0a, 0xed, 0x94, 0xba, 0x68,
	0x3b, 0xb5, 0x4c, 0xa1, 0xdd, 0x9a, 0x68, 0x27, 0x38, 0x6e, 0x41, 0x3d, 0x0e, 0xf9, 0x4c, 0xa6,
	0x5a, 0x15, 0x5e, 0x21, 0x86, 0x7a, 0x49, 0x4d, 0x9f, 0xc0, 0xf2, 0x69, 0x12, 0x6f, 0x8f, 0xb9,
	0x41, 0xff, 0x42, 0xd5, 0x55, 0x85, 0x6e, 0x4c, 0x42, 0x27, 0x47, 0xb0, 0x92, 0xd1, 0x95, 0xf5,
	0xdd, 0x87, 0x85, 0x80, 0x85, 0xd1, 0x15, 0x0f, 0x2d, 0x53, 0x54, 0x6d, 0x51, 0x55, 0xcd, 0x11,
	0xb0, 0xa3, 0xc4, 0xe4, 0x97, 0x01, 0xd5, 0x04, 0xc3, 0x1d, 0x68, 0xa8, 0xda, 0x45, 0x91, 0xae,
	0x5e, 0x5d, 0x62, 0x5f, 0x22, 0x4f, 0x0c, 0x7d, 0xdf, 0xe5, 0xec, 0xdc, 0x0f, 0xc6, 0xb2, 0x86,
	0xfa, 0xfe, 0x6f, 0x2c, 0x86, 0x7b, 0xb0, 0xe0, 0x0d, 0x29, 0xfb, 0xc9, 0x54, 0x64, 0x7a, 0x3e,
	0xbb, 0x31, 0xec, 0x28, 0x29, 0xe9, 0x80, 0x29, 0x10, 0x5c, 0x06, 0x53, 0x60, 0x22, 0x1e, 0xd3,
	0x49, 0x2e, 0x87, 0x7f, 0x4c, 0xa8, 0xf6, 0x04, 0xdd, 0xe3, 0x5b, 0xa8, 0xa7, 0xb8, 0x19, 0x6d,
	0x65, 0x70, 0x96, 0xf5, 0xed, 0x87, 0xb9, 0x32, 0xb9, 0x99, 0xf7, 0xf0, 0x15, 0xd4, 0x34, 0x65,
	0xa0, 0xa5, 0x74, 0xb3, 0x4c, 0x63, 0xaf, 0xe7, 0x48, 0xb4, 0x8d, 0x77, 0xd0, 0x48, 0xd3, 0x34,
	0x6a, 0x97, 0x39, 0x1f, 0x0a, 0x7b, 0x23, 0x5f, 0xa8, 0x8d, 0x7d, 0x86, 0x07, 0x19, 0x4a, 0xc6,
	0xcd, 0x49, 0x27, 0xf3, 0x48, 0xdf, 0xde, 0x2a, 0x94, 0x6b, 0xab, 0x5f, 0xa1, 0x95, 0xa5, 0x27,
	0x4c, 0x3d, 0xcb, 0xa5, 0x47, 0x7b, 0xbb, 0x58, 0x41, 0x1b, 0xbe, 0x82, 0xb5, 0x02, 0xe6, 0xc6,
	0xc7, 0xea, 0xf9, 0xfc, 0xef, 0x88, 0xbd, 0x77, 0xab, 0x9e, 0xf6, 0xf6, 0x12, 0x6a, 0x9a, 0x59,
	0x26, 0xdd, 0xca, 0x12, 0xd2, 0xa4, 0x5b, 0xb3, 0x34, 0x44, 0x61, 0x25, 0x97, 0x4c, 0xf1, 0x51,
	0xfa, 0x4d, 0x11, 0x55, 0xdb, 0xbb, 0xb7, 0x68, 0x49, 0x2f, 0x1f, 0xa0, 0x39, 0xb5, 0xa5, 0xa8,
	0xbb, 0x9e, 0xb7, 0xe8, 0x76, 0xa7, 0x40, 0xaa, 0xf2, 0x3e, 0x6c, 0x00, 0x9c, 0x46, 0x41, 0xff,
	0xc2, 0x0d, 0xbd, 0xe1, 0xf9, 0xb7, 0xaa, 0xf8, 0xdb, 0x79, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff,
	0xf9, 0x4d, 0x77, 0xf1, 0xfd, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SupplyClient is the client API for Supply service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SupplyClient interface {
	// Ordering
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	SendOrder(ctx context.Context, in *SendOrderRequest, opts ...grpc.CallOption) (*SendOrderResponse, error)
	AddOrderItem(ctx context.Context, in *AddOrderItemRequest, opts ...grpc.CallOption) (*AddOrderItemResponse, error)
	RemoveOrderItem(ctx context.Context, in *RemoveOrderItemRequest, opts ...grpc.CallOption) (*RemoveOrderItemResponse, error)
	ReceiveOrderItem(ctx context.Context, in *ReceiveOrderItemRequest, opts ...grpc.CallOption) (*ReceiveOrderItemResponse, error)
	ModifyRequestedQuantity(ctx context.Context, in *ModifyRequestedQuantityRequest, opts ...grpc.CallOption) (*ModifyRequestedQuantityResponse, error)
	FindOrder(ctx context.Context, in *FindOrderRequest, opts ...grpc.CallOption) (*FindOrderResponse, error)
	FindProjectOrderDates(ctx context.Context, in *FindProjectOrderDatesRequest, opts ...grpc.CallOption) (*FindProjectOrderDatesResponse, error)
	// ProductSearch
	ProductSearch(ctx context.Context, in *ProductSearchRequest, opts ...grpc.CallOption) (*ProductSearchResponse, error)
}

type supplyClient struct {
	cc *grpc.ClientConn
}

func NewSupplyClient(cc *grpc.ClientConn) SupplyClient {
	return &supplyClient{cc}
}

func (c *supplyClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) SendOrder(ctx context.Context, in *SendOrderRequest, opts ...grpc.CallOption) (*SendOrderResponse, error) {
	out := new(SendOrderResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/SendOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) AddOrderItem(ctx context.Context, in *AddOrderItemRequest, opts ...grpc.CallOption) (*AddOrderItemResponse, error) {
	out := new(AddOrderItemResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/AddOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) RemoveOrderItem(ctx context.Context, in *RemoveOrderItemRequest, opts ...grpc.CallOption) (*RemoveOrderItemResponse, error) {
	out := new(RemoveOrderItemResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/RemoveOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) ReceiveOrderItem(ctx context.Context, in *ReceiveOrderItemRequest, opts ...grpc.CallOption) (*ReceiveOrderItemResponse, error) {
	out := new(ReceiveOrderItemResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/ReceiveOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) ModifyRequestedQuantity(ctx context.Context, in *ModifyRequestedQuantityRequest, opts ...grpc.CallOption) (*ModifyRequestedQuantityResponse, error) {
	out := new(ModifyRequestedQuantityResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/ModifyRequestedQuantity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) FindOrder(ctx context.Context, in *FindOrderRequest, opts ...grpc.CallOption) (*FindOrderResponse, error) {
	out := new(FindOrderResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/FindOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) FindProjectOrderDates(ctx context.Context, in *FindProjectOrderDatesRequest, opts ...grpc.CallOption) (*FindProjectOrderDatesResponse, error) {
	out := new(FindProjectOrderDatesResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/FindProjectOrderDates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplyClient) ProductSearch(ctx context.Context, in *ProductSearchRequest, opts ...grpc.CallOption) (*ProductSearchResponse, error) {
	out := new(ProductSearchResponse)
	err := c.cc.Invoke(ctx, "/server.Supply/ProductSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server is the server API for Supply service.
type SupplyServer interface {
	// Ordering
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	SendOrder(context.Context, *SendOrderRequest) (*SendOrderResponse, error)
	AddOrderItem(context.Context, *AddOrderItemRequest) (*AddOrderItemResponse, error)
	RemoveOrderItem(context.Context, *RemoveOrderItemRequest) (*RemoveOrderItemResponse, error)
	ReceiveOrderItem(context.Context, *ReceiveOrderItemRequest) (*ReceiveOrderItemResponse, error)
	ModifyRequestedQuantity(context.Context, *ModifyRequestedQuantityRequest) (*ModifyRequestedQuantityResponse, error)
	FindOrder(context.Context, *FindOrderRequest) (*FindOrderResponse, error)
	FindProjectOrderDates(context.Context, *FindProjectOrderDatesRequest) (*FindProjectOrderDatesResponse, error)
	// ProductSearch
	ProductSearch(context.Context, *ProductSearchRequest) (*ProductSearchResponse, error)
}

func RegisterSupplyServer(s *grpc.Server, srv SupplyServer) {
	s.RegisterService(&_Supply_serviceDesc, srv)
}

func _Supply_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).SendOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/SendOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).SendOrder(ctx, req.(*SendOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_AddOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).AddOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/AddOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).AddOrderItem(ctx, req.(*AddOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_RemoveOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).RemoveOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/RemoveOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).RemoveOrderItem(ctx, req.(*RemoveOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_ReceiveOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).ReceiveOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/ReceiveOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).ReceiveOrderItem(ctx, req.(*ReceiveOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_ModifyRequestedQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRequestedQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).ModifyRequestedQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/ModifyRequestedQuantity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).ModifyRequestedQuantity(ctx, req.(*ModifyRequestedQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_FindOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).FindOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/FindOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).FindOrder(ctx, req.(*FindOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_FindProjectOrderDates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindProjectOrderDatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).FindProjectOrderDates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/FindProjectOrderDates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).FindProjectOrderDates(ctx, req.(*FindProjectOrderDatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supply_ProductSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplyServer).ProductSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Supply/ProductSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplyServer).ProductSearch(ctx, req.(*ProductSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Supply_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Supply",
	HandlerType: (*SupplyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Supply_CreateOrder_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _Supply_SendOrder_Handler,
		},
		{
			MethodName: "AddOrderItem",
			Handler:    _Supply_AddOrderItem_Handler,
		},
		{
			MethodName: "RemoveOrderItem",
			Handler:    _Supply_RemoveOrderItem_Handler,
		},
		{
			MethodName: "ReceiveOrderItem",
			Handler:    _Supply_ReceiveOrderItem_Handler,
		},
		{
			MethodName: "ModifyRequestedQuantity",
			Handler:    _Supply_ModifyRequestedQuantity_Handler,
		},
		{
			MethodName: "FindOrder",
			Handler:    _Supply_FindOrder_Handler,
		},
		{
			MethodName: "FindProjectOrderDates",
			Handler:    _Supply_FindProjectOrderDates_Handler,
		},
		{
			MethodName: "ProductSearch",
			Handler:    _Supply_ProductSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supply.proto",
}

// PurchasingClient is the client API for Purchasing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PurchasingClient interface {
}

type purchasingClient struct {
	cc *grpc.ClientConn
}

func NewPurchasingClient(cc *grpc.ClientConn) PurchasingClient {
	return &purchasingClient{cc}
}

// PurchasingServer is the server API for Purchasing service.
type PurchasingServer interface {
}

func RegisterPurchasingServer(s *grpc.Server, srv PurchasingServer) {
	s.RegisterService(&_Purchasing_serviceDesc, srv)
}

var _Purchasing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Purchasing",
	HandlerType: (*PurchasingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "supply.proto",
}
