// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ordering.proto

package ordering

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// CreateOrder
type CreateOrderRequest struct {
	OrderUuid            string   `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	ProjectUuid          string   `protobuf:"bytes,2,opt,name=project_uuid,json=projectUuid,proto3" json:"project_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{1}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetOrderUuid() string {
	if m != nil {
		return m.OrderUuid
	}
	return ""
}

func (m *CreateOrderRequest) GetProjectUuid() string {
	if m != nil {
		return m.ProjectUuid
	}
	return ""
}

type CreateOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{2}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

// AddOrderItem
type AddOrderItemRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uom                  string   `protobuf:"bytes,4,opt,name=uom,proto3" json:"uom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderItemRequest) Reset()         { *m = AddOrderItemRequest{} }
func (m *AddOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddOrderItemRequest) ProtoMessage()    {}
func (*AddOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{3}
}

func (m *AddOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderItemRequest.Unmarshal(m, b)
}
func (m *AddOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *AddOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderItemRequest.Merge(m, src)
}
func (m *AddOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddOrderItemRequest.Size(m)
}
func (m *AddOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderItemRequest proto.InternalMessageInfo

func (m *AddOrderItemRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *AddOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *AddOrderItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddOrderItemRequest) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

type AddOrderItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderItemResponse) Reset()         { *m = AddOrderItemResponse{} }
func (m *AddOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddOrderItemResponse) ProtoMessage()    {}
func (*AddOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{4}
}

func (m *AddOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderItemResponse.Unmarshal(m, b)
}
func (m *AddOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *AddOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderItemResponse.Merge(m, src)
}
func (m *AddOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddOrderItemResponse.Size(m)
}
func (m *AddOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderItemResponse proto.InternalMessageInfo

// RemoveOrderItem
type RemoveOrderItemRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrderItemRequest) Reset()         { *m = RemoveOrderItemRequest{} }
func (m *RemoveOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveOrderItemRequest) ProtoMessage()    {}
func (*RemoveOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{5}
}

func (m *RemoveOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrderItemRequest.Unmarshal(m, b)
}
func (m *RemoveOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *RemoveOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrderItemRequest.Merge(m, src)
}
func (m *RemoveOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveOrderItemRequest.Size(m)
}
func (m *RemoveOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrderItemRequest proto.InternalMessageInfo

func (m *RemoveOrderItemRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *RemoveOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type RemoveOrderItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrderItemResponse) Reset()         { *m = RemoveOrderItemResponse{} }
func (m *RemoveOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveOrderItemResponse) ProtoMessage()    {}
func (*RemoveOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{6}
}

func (m *RemoveOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrderItemResponse.Unmarshal(m, b)
}
func (m *RemoveOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *RemoveOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrderItemResponse.Merge(m, src)
}
func (m *RemoveOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveOrderItemResponse.Size(m)
}
func (m *RemoveOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrderItemResponse proto.InternalMessageInfo

// ModifyRequestedQuantity
type ModifyRequestedQuantityRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequestedQuantityRequest) Reset()         { *m = ModifyRequestedQuantityRequest{} }
func (m *ModifyRequestedQuantityRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRequestedQuantityRequest) ProtoMessage()    {}
func (*ModifyRequestedQuantityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{7}
}

func (m *ModifyRequestedQuantityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Unmarshal(m, b)
}
func (m *ModifyRequestedQuantityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Marshal(b, m, deterministic)
}
func (m *ModifyRequestedQuantityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequestedQuantityRequest.Merge(m, src)
}
func (m *ModifyRequestedQuantityRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyRequestedQuantityRequest.Size(m)
}
func (m *ModifyRequestedQuantityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequestedQuantityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequestedQuantityRequest proto.InternalMessageInfo

func (m *ModifyRequestedQuantityRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ModifyRequestedQuantityRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ModifyRequestedQuantityRequest) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ModifyRequestedQuantityResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequestedQuantityResponse) Reset()         { *m = ModifyRequestedQuantityResponse{} }
func (m *ModifyRequestedQuantityResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyRequestedQuantityResponse) ProtoMessage()    {}
func (*ModifyRequestedQuantityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{8}
}

func (m *ModifyRequestedQuantityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Unmarshal(m, b)
}
func (m *ModifyRequestedQuantityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Marshal(b, m, deterministic)
}
func (m *ModifyRequestedQuantityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequestedQuantityResponse.Merge(m, src)
}
func (m *ModifyRequestedQuantityResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyRequestedQuantityResponse.Size(m)
}
func (m *ModifyRequestedQuantityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequestedQuantityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequestedQuantityResponse proto.InternalMessageInfo

// SendOrder
type SendOrderRequest struct {
	OrderUuid            string   `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrderRequest) Reset()         { *m = SendOrderRequest{} }
func (m *SendOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SendOrderRequest) ProtoMessage()    {}
func (*SendOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{9}
}

func (m *SendOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrderRequest.Unmarshal(m, b)
}
func (m *SendOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrderRequest.Marshal(b, m, deterministic)
}
func (m *SendOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrderRequest.Merge(m, src)
}
func (m *SendOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SendOrderRequest.Size(m)
}
func (m *SendOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrderRequest proto.InternalMessageInfo

func (m *SendOrderRequest) GetOrderUuid() string {
	if m != nil {
		return m.OrderUuid
	}
	return ""
}

type SendOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrderResponse) Reset()         { *m = SendOrderResponse{} }
func (m *SendOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SendOrderResponse) ProtoMessage()    {}
func (*SendOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{10}
}

func (m *SendOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrderResponse.Unmarshal(m, b)
}
func (m *SendOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrderResponse.Marshal(b, m, deterministic)
}
func (m *SendOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrderResponse.Merge(m, src)
}
func (m *SendOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SendOrderResponse.Size(m)
}
func (m *SendOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrderResponse proto.InternalMessageInfo

// ReceiveOrderItem
type ReceiveOrderItemRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveOrderItemRequest) Reset()         { *m = ReceiveOrderItemRequest{} }
func (m *ReceiveOrderItemRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveOrderItemRequest) ProtoMessage()    {}
func (*ReceiveOrderItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{11}
}

func (m *ReceiveOrderItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveOrderItemRequest.Unmarshal(m, b)
}
func (m *ReceiveOrderItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveOrderItemRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveOrderItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveOrderItemRequest.Merge(m, src)
}
func (m *ReceiveOrderItemRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveOrderItemRequest.Size(m)
}
func (m *ReceiveOrderItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveOrderItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveOrderItemRequest proto.InternalMessageInfo

func (m *ReceiveOrderItemRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ReceiveOrderItemRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ReceiveOrderItemRequest) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ReceiveOrderItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveOrderItemResponse) Reset()         { *m = ReceiveOrderItemResponse{} }
func (m *ReceiveOrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveOrderItemResponse) ProtoMessage()    {}
func (*ReceiveOrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3965df4c9351bf43, []int{12}
}

func (m *ReceiveOrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveOrderItemResponse.Unmarshal(m, b)
}
func (m *ReceiveOrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveOrderItemResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveOrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveOrderItemResponse.Merge(m, src)
}
func (m *ReceiveOrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveOrderItemResponse.Size(m)
}
func (m *ReceiveOrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveOrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveOrderItemResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Empty)(nil), "ordering.Empty")
	proto.RegisterType((*CreateOrderRequest)(nil), "ordering.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "ordering.CreateOrderResponse")
	proto.RegisterType((*AddOrderItemRequest)(nil), "ordering.AddOrderItemRequest")
	proto.RegisterType((*AddOrderItemResponse)(nil), "ordering.AddOrderItemResponse")
	proto.RegisterType((*RemoveOrderItemRequest)(nil), "ordering.RemoveOrderItemRequest")
	proto.RegisterType((*RemoveOrderItemResponse)(nil), "ordering.RemoveOrderItemResponse")
	proto.RegisterType((*ModifyRequestedQuantityRequest)(nil), "ordering.ModifyRequestedQuantityRequest")
	proto.RegisterType((*ModifyRequestedQuantityResponse)(nil), "ordering.ModifyRequestedQuantityResponse")
	proto.RegisterType((*SendOrderRequest)(nil), "ordering.SendOrderRequest")
	proto.RegisterType((*SendOrderResponse)(nil), "ordering.SendOrderResponse")
	proto.RegisterType((*ReceiveOrderItemRequest)(nil), "ordering.ReceiveOrderItemRequest")
	proto.RegisterType((*ReceiveOrderItemResponse)(nil), "ordering.ReceiveOrderItemResponse")
}

func init() { proto.RegisterFile("ordering.proto", fileDescriptor_3965df4c9351bf43) }

var fileDescriptor_3965df4c9351bf43 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0x4f, 0xe2, 0x40,
	0x10, 0x3e, 0x0e, 0xee, 0xa0, 0x03, 0x77, 0xc7, 0x2d, 0x77, 0x50, 0xf6, 0x0e, 0x84, 0x7d, 0xc2,
	0x17, 0x12, 0xf5, 0x17, 0x18, 0xa3, 0x09, 0x89, 0x86, 0x58, 0xa3, 0x31, 0xf1, 0x81, 0x20, 0xbb,
	0x9a, 0x9a, 0xb4, 0x5b, 0xca, 0x2e, 0x09, 0x7f, 0xc5, 0x5f, 0x6b, 0xba, 0x2c, 0x4b, 0x81, 0xb6,
	0xd1, 0xc8, 0xdb, 0xee, 0xcc, 0xb7, 0xdf, 0x37, 0x33, 0xfd, 0xa6, 0xf0, 0x93, 0x87, 0x94, 0x85,
	0xae, 0xff, 0xdc, 0x0f, 0x42, 0x2e, 0x38, 0x2a, 0xad, 0xee, 0xa4, 0x08, 0xdf, 0xce, 0xbd, 0x40,
	0x2c, 0xc8, 0x1d, 0xa0, 0xb3, 0x90, 0x8d, 0x05, 0x1b, 0x46, 0x29, 0x87, 0x4d, 0x25, 0x9b, 0x09,
	0xd4, 0x02, 0x50, 0xd0, 0x91, 0x94, 0x2e, 0xb5, 0x73, 0x9d, 0x5c, 0xcf, 0x72, 0x2c, 0x15, 0xb9,
	0x95, 0x2e, 0x45, 0x5d, 0xa8, 0x04, 0x21, 0x7f, 0x61, 0x13, 0xb1, 0x04, 0x7c, 0x55, 0x80, 0xb2,
	0x8e, 0x45, 0x10, 0xf2, 0x17, 0x6a, 0x1b, 0xbc, 0xb3, 0x80, 0xfb, 0x33, 0x46, 0x24, 0xd4, 0x4e,
	0x29, 0x55, 0xb1, 0x81, 0x60, 0xde, 0x4a, 0xaf, 0x09, 0xcb, 0xd2, 0x46, 0x46, 0xad, 0xa8, 0xee,
	0x03, 0x1a, 0x95, 0x12, 0x84, 0x9c, 0xca, 0x89, 0x18, 0x19, 0x25, 0x4b, 0x47, 0x06, 0x14, 0x21,
	0x28, 0xf8, 0x63, 0x8f, 0xd9, 0x79, 0x95, 0x50, 0x67, 0x54, 0x85, 0xbc, 0xe4, 0x9e, 0x5d, 0x50,
	0xa1, 0xe8, 0x48, 0xea, 0xf0, 0x67, 0x53, 0x56, 0x97, 0xe3, 0x40, 0xdd, 0x61, 0x1e, 0x9f, 0xb3,
	0xfd, 0x55, 0x44, 0x9a, 0xd0, 0xd8, 0xe1, 0xd4, 0x72, 0x73, 0x68, 0x5f, 0x71, 0xea, 0x3e, 0x2d,
	0xb4, 0x0a, 0xa3, 0xd7, 0x72, 0xec, 0x0b, 0x57, 0x2c, 0x3e, 0x3f, 0x08, 0x0c, 0xa5, 0xa9, 0x26,
	0x53, 0xc3, 0xf8, 0xe1, 0x98, 0x3b, 0xe9, 0xc2, 0x41, 0xaa, 0xae, 0x2e, 0xed, 0x08, 0xaa, 0x37,
	0xcc, 0xa7, 0x1f, 0x70, 0x01, 0xa9, 0xc1, 0xef, 0xd8, 0x13, 0xcd, 0xc3, 0xa3, 0xee, 0x27, 0xcc,
	0xdd, 0xe7, 0x48, 0x33, 0x7b, 0xc3, 0x60, 0xef, 0x0a, 0x2e, 0x8b, 0x39, 0x7e, 0x2d, 0x80, 0xb1,
	0x3c, 0xba, 0x84, 0x72, 0xcc, 0x91, 0xe8, 0x7f, 0xdf, 0x2c, 0xc7, 0xee, 0x02, 0xe0, 0x56, 0x4a,
	0x56, 0x77, 0xf9, 0x05, 0x5d, 0x80, 0x65, 0x9a, 0x47, 0x78, 0x8d, 0xde, 0x1e, 0x22, 0xfe, 0x97,
	0x98, 0x33, 0x3c, 0x43, 0xa8, 0xc4, 0x9d, 0x89, 0x62, 0xc2, 0x09, 0x8b, 0x82, 0xdb, 0x69, 0x69,
	0x43, 0x78, 0x0f, 0xbf, 0xb6, 0xec, 0x87, 0x3a, 0xeb, 0x47, 0xc9, 0x6e, 0xc7, 0xdd, 0x0c, 0x84,
	0x61, 0x7e, 0x80, 0xea, 0xf6, 0xa4, 0xd1, 0xc6, 0xc3, 0xc4, 0xcf, 0x8e, 0x49, 0x16, 0xc4, 0x90,
	0x07, 0xd0, 0x48, 0xb1, 0x28, 0xea, 0xad, 0x09, 0xb2, 0xb7, 0x07, 0x1f, 0xbe, 0x03, 0xb9, 0x52,
	0x7c, 0xfc, 0xae, 0xfe, 0x89, 0x27, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0x9a, 0xbc, 0xf9,
	0x25, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderingClient is the client API for Ordering service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderingClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	SendOrder(ctx context.Context, in *SendOrderRequest, opts ...grpc.CallOption) (*SendOrderResponse, error)
	AddOrderItem(ctx context.Context, in *AddOrderItemRequest, opts ...grpc.CallOption) (*AddOrderItemResponse, error)
	RemoveOrderItem(ctx context.Context, in *RemoveOrderItemRequest, opts ...grpc.CallOption) (*RemoveOrderItemResponse, error)
	ReceiveOrderItem(ctx context.Context, in *ReceiveOrderItemRequest, opts ...grpc.CallOption) (*ReceiveOrderItemResponse, error)
	ModifyRequestedQuantity(ctx context.Context, in *ModifyRequestedQuantityRequest, opts ...grpc.CallOption) (*ModifyRequestedQuantityResponse, error)
}

type orderingClient struct {
	cc *grpc.ClientConn
}

func NewOrderingClient(cc *grpc.ClientConn) OrderingClient {
	return &orderingClient{cc}
}

func (c *orderingClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/ordering.ordering/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderingClient) SendOrder(ctx context.Context, in *SendOrderRequest, opts ...grpc.CallOption) (*SendOrderResponse, error) {
	out := new(SendOrderResponse)
	err := c.cc.Invoke(ctx, "/ordering.ordering/SendOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderingClient) AddOrderItem(ctx context.Context, in *AddOrderItemRequest, opts ...grpc.CallOption) (*AddOrderItemResponse, error) {
	out := new(AddOrderItemResponse)
	err := c.cc.Invoke(ctx, "/ordering.ordering/AddOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderingClient) RemoveOrderItem(ctx context.Context, in *RemoveOrderItemRequest, opts ...grpc.CallOption) (*RemoveOrderItemResponse, error) {
	out := new(RemoveOrderItemResponse)
	err := c.cc.Invoke(ctx, "/ordering.ordering/RemoveOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderingClient) ReceiveOrderItem(ctx context.Context, in *ReceiveOrderItemRequest, opts ...grpc.CallOption) (*ReceiveOrderItemResponse, error) {
	out := new(ReceiveOrderItemResponse)
	err := c.cc.Invoke(ctx, "/ordering.ordering/ReceiveOrderItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderingClient) ModifyRequestedQuantity(ctx context.Context, in *ModifyRequestedQuantityRequest, opts ...grpc.CallOption) (*ModifyRequestedQuantityResponse, error) {
	out := new(ModifyRequestedQuantityResponse)
	err := c.cc.Invoke(ctx, "/ordering.ordering/ModifyRequestedQuantity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderingServer is the server API for Ordering service.
type OrderingServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	SendOrder(context.Context, *SendOrderRequest) (*SendOrderResponse, error)
	AddOrderItem(context.Context, *AddOrderItemRequest) (*AddOrderItemResponse, error)
	RemoveOrderItem(context.Context, *RemoveOrderItemRequest) (*RemoveOrderItemResponse, error)
	ReceiveOrderItem(context.Context, *ReceiveOrderItemRequest) (*ReceiveOrderItemResponse, error)
	ModifyRequestedQuantity(context.Context, *ModifyRequestedQuantityRequest) (*ModifyRequestedQuantityResponse, error)
}

func RegisterOrderingServer(s *grpc.Server, srv OrderingServer) {
	s.RegisterService(&_Ordering_serviceDesc, srv)
}

func _Ordering_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderingServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordering.ordering/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderingServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ordering_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderingServer).SendOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordering.ordering/SendOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderingServer).SendOrder(ctx, req.(*SendOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ordering_AddOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderingServer).AddOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordering.ordering/AddOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderingServer).AddOrderItem(ctx, req.(*AddOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ordering_RemoveOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderingServer).RemoveOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordering.ordering/RemoveOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderingServer).RemoveOrderItem(ctx, req.(*RemoveOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ordering_ReceiveOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderingServer).ReceiveOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordering.ordering/ReceiveOrderItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderingServer).ReceiveOrderItem(ctx, req.(*ReceiveOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ordering_ModifyRequestedQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRequestedQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderingServer).ModifyRequestedQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordering.ordering/ModifyRequestedQuantity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderingServer).ModifyRequestedQuantity(ctx, req.(*ModifyRequestedQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ordering_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ordering.ordering",
	HandlerType: (*OrderingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Ordering_CreateOrder_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _Ordering_SendOrder_Handler,
		},
		{
			MethodName: "AddOrderItem",
			Handler:    _Ordering_AddOrderItem_Handler,
		},
		{
			MethodName: "RemoveOrderItem",
			Handler:    _Ordering_RemoveOrderItem_Handler,
		},
		{
			MethodName: "ReceiveOrderItem",
			Handler:    _Ordering_ReceiveOrderItem_Handler,
		},
		{
			MethodName: "ModifyRequestedQuantity",
			Handler:    _Ordering_ModifyRequestedQuantity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ordering.proto",
}
