// Code generated by protoc-gen-go. DO NOT EDIT.
// source: purchasing.proto

package ordering

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("purchasing.proto", fileDescriptor_f3d74dfbb927d1c0) }

var fileDescriptor_f3d74dfbb927d1c0 = []byte{
	// 57 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0x2d, 0x4a,
	0xce, 0x48, 0x2c, 0xce, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x2f,
	0x4a, 0x49, 0x2d, 0xca, 0xcc, 0x4b, 0x4f, 0x62, 0x03, 0x0b, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x19, 0x80, 0x50, 0x3d, 0x24, 0x00, 0x00, 0x00,
}
