// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"field/pkg/grpc"
	"field/pkg/inmem"
)

// Injectors from wire.go:

func initializeFieldServicesInMemory() *grpc.Service {
	orderRepository := inmem.NewOrderRepository()
	service := grpc.NewOrderingService(orderRepository)
	return service
}
