// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AddOrderItem struct {
	OrderID   string `json:"orderID"`
	ProductID string `json:"productID"`
	Name      string `json:"name"`
	Uom       string `json:"uom"`
}

type CloseProject struct {
	ProjectID string `json:"projectID"`
}

type CreateOrder struct {
	OrderID   string `json:"orderID"`
	ProjectID string `json:"projectID"`
	Name      string `json:"name"`
}

type CreateProject struct {
	ProjectID string `json:"projectID"`
	Name      string `json:"name"`
}

type ModifyQuantity struct {
	OrderID   string `json:"orderID"`
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type RemoveOrderItem struct {
	OrderID   string `json:"orderID"`
	ProductID string `json:"productID"`
}

type SendOrder struct {
	OrderID string `json:"orderID"`
}
