// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"field/pkg/ordering"
	"field/pkg/postgres"
)

// Injectors from wire.go:

func initializeFieldServices(db *sql.DB) *ordering.Service {
	orderRepository := postgres.NewOrderRepository(db)
	service := ordering.NewOrderingService(orderRepository)
	return service
}
