// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"field/supply/grpc"
	mongo2 "field/supply/mongo"
	"field/supply/ordering"
	"field/supply/purchasing"
	"field/supply/search"
	"github.com/mongodb/mongo-go-driver/mongo"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeSupplyServices(db *mongo.Database) (*grpc.Server, error) {
	orderRepository := mongo2.NewOrderRepository(db)
	service := ordering.NewOrderingService(orderRepository)
	productRepository := mongo2.NewProductRepository(db)
	purchasingService, err := purchasing.NewPurchasingService(productRepository, orderRepository)
	if err != nil {
		return nil, err
	}
	searchService, err := search.NewSearchService(productRepository)
	if err != nil {
		return nil, err
	}
	grpcServer := server.New(service, purchasingService, searchService)
	return grpcServer, nil
}
